services:

  backend:
    container_name: backend
    build:
      context: ./backend
      target: dev
      dockerfile: Dockerfile
    ports:
      - "3001:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000 
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_WATCH_SUPPRESS_BROWSER_LAUNCH=true
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${USER_POSTGRES};Password=${PASSWORD_POSTGRES}
    volumes:
      - ./backend:/src:z
      - ./backend_bin:/src/**/bin
      - ./backend_obj:/src/**/obj

    command: dotnet watch run --urls=http://+:5000
    networks:
      - backend
    restart:
      unless-stopped

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: dev
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:z
      - /app/node_modules
      - /app/.next
    networks:
      - frontend
      - backend
    restart: unless-stopped
  
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=${USER_POSTGRES}
      - POSTGRES_PASSWORD=${PASSWORD_POSTGRES}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - backend
    restart:
      unless-stopped
  
  adminer:
    container_name: adminer
    image: adminer:latest
    ports:
      - "8080:8080"
    networks:
      - backend
    restart:
      unless-stopped

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
volumes:
  pgdata: